Ruby/proyectoFinal/config/routes.rb
Rails.application.routes.draw do  
  
  root 'pets#index'

  get 'mascotas/buscar' => 'pets#search', as: :search_pet

  get 'usuario/mis_mascotas' => 'pets#my_pets', as: :my_pets_pet
  get 'mascotas/:id/interesados' => 'pets#list_interested', as: :list_interested_pet
  get 'usuario/nuevo_dueño' => 'pets#new_owner', as: :new_owner_pet
  get 'mascota/:id/solicitud' => 'pets#show_request', as: :show_request_pet
  post 'distancia' => 'pets#show_distance', as: :distance

  resources :solicituds,
    path: 'solicitud',
    path_names: { new:'nueva', edit: "editar", create:'nueva'}

  resources :pets,
    path: 'mascotas',
    path_names: { new: "nueva", edit: "editar"}

  devise_for :users,
    controllers: { sessions: "users/sessions", registrations: 'users/registrations',
                   confirmations: "users/confirmations", passwords: 'users/passwords',
                   omniauth_callbacks: 'omniauth_callbacks'}, 
    path: "/", 
    path_names: { sign_in: 'ingresar', password: 'contraseña', sign_out: 'salir',
                  registration: 'registrarme', sign_up: '/', confirmation: 'confirmacion'}

  devise_scope :user do
    get 'dislike' => 'pets#notInterested', as: :desinteresado
    get 'like' => 'pets#interested', as: :interesado
    get 'contraseña/nueva' => 'users/passwords#new',  as: :new_password
    post 'contraseña/nueva' => 'users/passwords#create', as: :password
    get 'contraseña/editar' => 'users/passwords#edit', as: :edit_password
    match 'contraseña/editar' => 'users/passwords#update', via: [:put, :patch], as: :update_password
    get 'usuario/editar' => 'users/registrations#edit', as: :edit_user
    match 'usuario/editar' => 'users/registrations#update', via: [:put, :patch], as: :update_user
    get 'usuario/' => 'user#index', as: :user
    get 'confirmacion' => 'users/confirmations#new', as: :new_confirmation
  end
    

end

Ruby/proyectoFinal/app/models/pet.rb
class Pet < ActiveRecord::Base

	belongs_to :user	

	extend Enumerize
	extend FriendlyId
	
    acts_as_followable    

    friendly_id :id, use: :slugged
	friendly_id :name, use: [:slugged, :finders]

	validates :name, :race, :height, :specie, :imagen, :sex, :longitude, :latitude, presence: true
	validates :age, numericality: { greater_than_or_equal_to: 1 }
	
	validates :description, presence: { message: "Debes dar una descripción de la mascota" }

	
	enumerize :sex, in: [:macho , :hembra]
	enumerize :height, in: [:pequeño, :mediano, :grande]

	mount_uploader :imagen, ImageUploader

	validate :image_size_validation 

	acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

	def slug_candidates
      [:name,       	
      	[:name, :id_for_slug],      
      ]
    end

  	def id_for_slug
      generated_slug = normalize_friendly_id(name)
      things = self.class.where('slug LIKE :pattern', pattern: "#{generated_slug}(-[0-9]+)?$")
      things = things.where.not(id: id) unless new_record?
      things.count + 1
  	end
	
	private
	def image_size_validation
    	errors[:imagen] << "should be less than 500KB" if imagen.size > 0.5.megabytes
    end

end

Ruby/proyectoFinal/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :log_in?, only: [:index]

  # Check if exist a logged in user and redirect to user index page
  def log_in?
    if current_user
      redirect_to user_path
    end
  end

  # GET /pets
  # GET /pets.json
  def index
    @title = 'Mascotas'
    @pets = Pet.where(adpted: 'f').page(params[:page]).per(3)
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @title = @pet.name + ' | Mascotas' 
    @owner = User.find(@pet.user_id)
  end

  # GET /pets/new
  def new
    @title = 'Nueva mascota | Mascotas' 
    @pet = Pet.new(name: FFaker::Name.name, description: FFaker::Lorem.paragraph)
  end

  # GET /pets/1/edit
  def edit
    if current_user.id != @pet.user_id
      redirect_to user_path
    end
  end
  
  def notInterested
    @pet = Pet.find(params[:id])
    @title = @pet.name + ' | Mascotas'
    user = User.find(current_user.id)
    user.stop_following(@pet)
    render :show
  end  


  def interested
    @pet = Pet.find(params[:id])
    @title = @pet.name + ' | Mascotas' 
    user = User.find(current_user.id)
    user.follow(@pet)
    render :show
  end  

  def list_interested          
    @pet = Pet.find(params[:id])            
    @hash = [{lat: current_user.latitude, lng: current_user.longitude, infowindow: 'Tú'}]
    render :list_interested
  end  

  def new_owner
    @pet = Pet.find(params[:id])
    @user = User.find(params[:no])
    @pet.adpted = true
    @pet.new_owner = @user.id
    @pet.save
    render :new_owner
  end  

  def my_pets
    user = User.find(current_user.id)
    @pets = Pet.where(user_id: user.id).page(params[:page]).per(3)
    render :my_pets
  end

  def show_request
    @solicitud = Solicitud.find(params[:id])
    render :show_request
  end
  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    @pet.latitude = current_user.latitude
    @pet.longitude = current_user.longitude
    respond_to do |format|
      if @pet.save
        pet = Pet.find(@pet.id)
        user = User.find(current_user.id)
        format.html { redirect_to @pet, notice: 'Mascota fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # Method to find pets, receive a parameter
  def search
    @kms = params[:kms]
    if current_user
      @pets = Pet.where.not(user_id: current_user.id, adpted: 't').within(@kms.to_i, :origin=>[19.3234472,-99.1796417])
      @hash = Gmaps4rails.build_markers(@pets) do |pet, marker|
        marker.lat pet.latitude
        marker.lng pet.longitude
        marker.infowindow '<a style="font-size:18px" href="'+pet_path(pet)+'">'+pet.name+'</a>'
      end
    else
      @pets = Pet.where(adpted: 'f').within(@kms.to_i, :origin=>[19.3234472,-99.1796417])
      @hash = Gmaps4rails.build_markers(@pets) do |pet, marker|
        marker.lat pet.latitude
        marker.lng pet.longitude
        marker.infowindow '<a style="font-size:18px" href="'+pet_path(pet)+'">'+pet.name+'</a>'
      end
    end
    @hash << { "lat":19.3234472, "lng":-99.1796417, "infowindow":'<div style="font-size:18px">Aqui estas tu</div> ' }
    puts @hash.to_json
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Mascota fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_distance
    @user = User.find(params[:id])
    msg = [{ lat: @user.latitude, lng: @user.longitude, 
             infowindow: '<p>'+@user.given_name+'</p><p>'+@user.address+'</p>' }, 
           {lat: current_user.latitude, lng: current_user.longitude, infowindow: 'Tú'}]
    render :json => msg
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :specie, :sex, :race, :height, :sterilization, :adpted, :description, :imagen)
    end
end

Ruby/proyectoFinal/app/helpers/pets_helper.rb
module PetsHelper
end

Ruby/proyectoFinal/app/views/pets/edit.html.erb
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div clas="container">
          <a class="navbar-brand" href="">
            <i class="fa fa-rocket fa-4"></i>
            <div class="content-hidden">Mascotas</div>
          </a>
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to user_path, :class => 'nav-link' do%>
                <%= fa_icon "home"%> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to my_pets_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "list"%> <div class="content-hidden">Mis Publicaciones</div>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to new_pet_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square" %> <div class="content-hidden">Publicar</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to edit_user_path, class:"nav-link" do %>
                <%= fa_icon "pencil" %> <div class="content-hidden">Editar Cuenta</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: 'delete', class:"nav-link" do %>
                <%= fa_icon "sign-out" %> <div class="content-hidden">Salir</div>
              <% end %>
            </li>
          </ul>
        </div><!-- bs-example-navbar-collapse-1 -->
      </nav>
    <br><br> <!-- Agregar espacio entre el header y body-->	
    <nav>
      <ul class="pager">
        <li><%= link_to '« Regresar', pets_path %></li>          
      </ul>
    </nav>
	<%= render 'form' %>	

Ruby/proyectoFinal/app/views/pets/list_interested.html.erb
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div clas="container">
          <a class="navbar-brand" href="">
            <i class="fa fa-paw fa-4"></i>
            <div class="content-hidden">Mascotas</div>
          </a>
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to user_path, :class => 'nav-link' do%>
                <%= fa_icon "home"%> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path(kms: 5), :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to my_pets_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "list"%> <div class="content-hidden">Mis Publicaciones</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to new_pet_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square" %> <div class="content-hidden">Publicar</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to edit_user_path, class:"nav-link" do %>
                <%= fa_icon "pencil" %> <div class="content-hidden">Editar Cuenta</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: 'delete', class:"nav-link" do %>
                <%= fa_icon "sign-out" %> <div class="content-hidden">Salir</div>
              <% end %>
            </li>
          </ul>
        </div><!-- bs-example-navbar-collapse-1 -->
      </nav>

      <div id="wrapper">
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="container">
            <br/>
            <nav>
              <ul class="pager">
                <li><%= link_to '« Regresar', pet_path(@pet) %></li>
              </ul>
            </nav>

            <div class="row">

            <br/>
            <br/>
            <h4 class="omb_authTitle" style="text-align:center">Interesados</h4>

            <% if @pet.followers_count > 0 %>
            <div class="row">
              <center>                
                <table style="width:100%">
                   <tr>
                    <th>Nombre Competo</th>
                    <th>Correo</th>
                    <th>Telefono</th>
                    <th>Dirección</th>
                    <th>Solicitud</th>
                    <th>Seleccionar</th>
                  </tr>                                                                        
                <% @pet.followers.each do |f| %>
                  <tr>
                    <td> <%= f.given_name %> <%= f.first_surname %> <%= f.second_surname %></td>
                    <td> <%= f.email %> </td> 
                    <td> <%= f.phone_number%> </td>
                    <td> <%= link_to 'Ver mapa', distance_path(id: f.id), class: 'dist' %> </td> 
                    <% if Solicitud.where(id_pet: @pet.id,id: f.id ) == [] %>
                    <td>
                      No hay solicitud
                    </td>
                    <td>
                      <%= link_to 'Nuevo dueño', new_owner_pet_path(id: @pet, no: f.id), class:"btn btn-secondary disabled" %>
                    </td>
                    <% else %>                        
                    <td>
                      <%= link_to 'Ya tiene solicitud', solicitud_path(id: f.id) %>
                    </td>
                    <td>
                      <%= link_to 'Nuevo dueño', new_owner_pet_path(id: @pet, no: f.id), class:"btn btn-primary" %>
                    </td>
                    <% end %>                                        
                  </tr>
                <% end %>
                </table>
              </center>
            </div>
            <div class="row">
              <div class="col-sm-offset-1 col-sm-10">
                <div id="map" style="margin-top: 20px; width:100%; height:450px;"></div>
              </div>
            </div>
            <% else %>
            No se encontraron seguidores
            <% end %>
          </div>
        </div>
      </div><!-- /#wrapper -->

      <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=®ion="></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"></script>

      <script>
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
      $('.dist').click(function(e) {
        urls = $(this).attr('href');
        $.ajax({
          url: urls,
          type: "POST",
          success: function(data){
            console.log(data);
            handler = Gmaps.build('Google');
            handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
              markers = handler.addMarkers(data);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
            });
          }
        });
        e.preventDefault();
      });
      </script>

Ruby/proyectoFinal/app/views/pets/my_pets.html.erb
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div clas="container">
          <a class="navbar-brand" href="">
            <i class="fa fa-paw fa-4"></i>
            <div class="content-hidden">Mascotas</div>
          </a>
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to user_path, :class => 'nav-link' do%>
                <%= fa_icon "home"%> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path(kms: 5), :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to my_pets_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "list"%> <div class="content-hidden">Mis Publicaciones</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to new_pet_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square" %> <div class="content-hidden">Publicar</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to edit_user_path, class:"nav-link" do %>
                <%= fa_icon "pencil" %> <div class="content-hidden">Editar Cuenta</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: 'delete', class:"nav-link" do %>
                <%= fa_icon "sign-out" %> <div class="content-hidden">Salir</div>
              <% end %>
            </li>
          </ul>
        </div><!-- bs-example-navbar-collapse-1 -->
      </nav>
      
      <div id="wrapper">
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="container">

            <div class="alert alert-success" role="alert" hidden>
              <%= notice %>
            </div>

            <br/>

            <nav>
              <ul class="pager">
                <li><%= link_to '« Regresar', pets_path %></li>          
              </ul>
            </nav>

            <center><h3>Mis mascotas</h3></center>
            
            <div class="row">
              <% @pets.each do |pet| %>
                <div class="col-sm-6 col-md-4" style="margin-top:20px;">
                  <hr class="post"/>
                  <div class="card-image">
                    <center> <%=image_tag pet.imagen.thumb.url, class: "card-img-top" %> </center>
                  </div>
                  <div class="card-block">
                    <h4 class="card-title"><%= pet.name %></h4>
                    <p><%= pet.specie %>: <%= pet.race %></p>
                    <%if pet.adpted == false %>
                      <p class="card-text message"><%= pet.description %></p>
                    <%else%>
                      <p class="card-text message text-success">
                        ¡YA TIENE HOGAR! =)
                      </p>
                    <%end%>
                    <%= link_to 'Ver publicación »', pet, class:"btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            </div>

            <center>
              <%= paginate(@pets) %>
            </center>

          </div><!-- /#page-content-wrapper -->
        </div><!-- /#wrapper -->
      </div>

Ruby/proyectoFinal/app/views/pets/show.html.erb
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div clas="container">
          <a class="navbar-brand" href="">
            <i class="fa fa-paw fa-4"></i>
            <div class="content-hidden">Mascotas</div>
          </a>
          <% if current_user %> <!-- Si el usuario inicio sesion -->
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to user_path, :class => 'nav-link' do%>
                <%= fa_icon "home"%> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path(kms: 5), :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to my_pets_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "list"%> <div class="content-hidden">Mis Publicaciones</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_pet_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square" %> <div class="content-hidden">Publicar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to edit_user_path, class:"nav-link" do %>
                <%= fa_icon "pencil" %> <div class="content-hidden">Editar Cuenta</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: 'delete', class:"nav-link" do %>
                <%= fa_icon "sign-out" %> <div class="content-hidden">Salir</div>
              <% end %>
            </li>
          </ul>
          <% else %> <!-- Si el usuario no inicio sesion -->
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to root_path, :class => 'nav-link' do%>
                <%= fa_icon "home" %> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path(kms: 5), :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, :class => 'nav-link' do%>
                <%= fa_icon "sign-in" %> <div class="content-hidden">Ingresa</div>
              <% end %>
            </li>
          
            <li class="nav-item">
              <%= link_to new_user_registration_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square-o" %> <div class="content-hidden">Registrate</div>
              <% end %>
            </li>
          </ul>
          <% end %>
        </div> <!-- fin de nav -->
      </nav>

      
      <br/><br/> <!-- Agregar espacio entre el header y body--> 

      <nav>
        <ul class="pager">
          <li><%= link_to '« Inicio', root_path %></li>
        </ul>
      </nav>

      <div id="wrapper">
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="container">

            <div class="row">
              <div class="col-sm-12 col-md-6 col-lg-5">
                <center>
                   <%=image_tag @pet.imagen.url, class: "imagen-mascota" %>
                </center>
              </div>
              <div class="col-sm-12 col-md-6 col-lg-7">
                <h2 style="text-align:center"><strong><%= @pet.name %></strong></h2>  

                <div class="col-lg-offset-1 col-sm-12 col-lg-10">
                  <p>
                  <% if @pet.new_owner then owner = User.find(@pet.new_owner) else owner = User.find(@pet.user_id) end %>
                  <% if @pet.new_owner %>
                    <div class="alert alert-info" role="alert"> Esta mascota fue adoptada
                    </div>
                    <strong>Nuevo Dueño: </strong> <%= owner.given_name %>
                  <% else %><!-- Show owner's name -->
                    <strong>Dueño: </strong> <%= owner.given_name %>
                  <% end %>
                  </p>
                  <p style="text-align: justify">
                    <strong>Especie: </strong> <%= @pet.specie %>
                    <strong>Raza: </strong> <%= @pet.race %>
                    <strong>Sexo: </strong> <%= @pet.sex %>
                  </p>
                  <p>
                    <strong>Descripción: </strong> <%= @pet.description %>
                  </p>
                  <p style="text-align:center">
                    <strong>No. de Interesados <%= @pet.followers_count %></strong> 
                  </p>
                </div>
              </div>
              <div class="col-lg-offset-1 col-sm-12 col-lg-10" style="text-align:center">
                <p>
                  <strong >Edad: </strong> <%= @pet.age %> <br/>
                  <strong>Tamaño: </strong> <%= @pet.height %> <br/>
                  <% if @pet.sterilization? then sterilization = 'Sí' else sterilization =  'No' end %>
                  <strong>Esterilizado: <%= sterilization  %></strong> <br/>
                  <strong>Direccion: </strong> <%= owner.address %>
                </p>
                <p style="text-align:center">
                  <% if user_signed_in? %> <!-- If is logged in -->
                    <% if current_user.id == @pet.user_id and !@pet.new_owner %> <!-- Is the owner but not new owner -->
                      <%= link_to list_interested_pet_path(id: @pet), :class => 'btn btn-secondary' do %>
                        <%= fa_icon "users" %> Ver Interesados
                      <% end %> <!-- Can see list of interested -->
                      <%= link_to edit_pet_path(@pet), :class => 'btn btn-secondary' do %>
                        <%= fa_icon "pencil-square" %> Editar
                      <% end %> <!-- Can edit -->
                    <% else %>
                      <% if User.find(current_user.id).following?(@pet) %> <!-- Isn't owner and is interested in pet -->
                        <p style="text-align: center">
                          Esta mascota te interesa puedes dejar de seguirla o mandar solicitud, solo puedes mandar una solicitud a la vez, si ya enviaste una ya no podras mandar mas a otras mascotas
                        </p>
                        <% if Solicitud.where(id: current_user) == [] %> <!-- Interested and solicitud sent -->
                          <%= link_to desinteresado_path(id: @pet),  :class => 'btn btn-secondary' do %>
                            <%= fa_icon "times" %> Ya no me interesa
                          <% end %> <!-- Uninterest -->
                          <%= link_to new_solicitud_path(id: @pet), :class => 'btn btn-secondary' do %>
                            <%= fa_icon "arrow" %> Llenar solicitud
                          <% end %> <!-- Send solicitud -->

                        <% else %> <!-- Solicitud sent -->
                          <%= link_to desinteresado_path(id: @pet), :class => 'btn btn-secondary' do %>
                            <%= fa_icon "times" %> Ya no me interesa
                          <% end %> <!-- Uninterest -->
                          Ya has enviado una solicitud
                        <% end %>
                      <% else %> <!-- Not interested -->
                        <% if current_user.id != @pet.user_id %> <!-- Logged in and not interested -->
                          <%= link_to interesado_path(id: @pet), :class => 'btn btn-secondary' do %>
                            <%= fa_icon "paw" %> Me interesa
                          <% end %> <!-- Uninterest -->
                        <% end %>
                      <% end %>
                    <%end%>
                  <% else %>
                    Debes registrarte para poder adoptar
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div><!-- /#page-content-wrapper -->
      </div><!-- /#wrapper -->

Ruby/proyectoFinal/app/views/pets/show_distance.html.erb
      <div id="map" style="width:100%; height:450px;"></div>

      <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=®ion="></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"></script>

      <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
      </script>