Ruby/proyectoFinal/config/routes.rb
Rails.application.routes.draw do  
  
  root 'pets#index'

  get 'mascotas/buscar' => 'pets#search', as: :search_pet

  get 'usuario/mis_mascotas' => 'pets#my_pets', as: :my_pets_pet
  get 'mascotas/:id/interesados' => 'pets#list_interested', as: :list_interested_pet
  get 'usuario/nuevo_dueño' => 'pets#new_owner', as: :new_owner_pet
  get 'mascota/:id/solicitud' => 'pets#show_request', as: :show_request_pet
  post 'distancia' => 'pets#show_distance', as: :distance

  resources :solicituds,
    path: 'solicitud',
    path_names: { new:'nueva', edit: "editar", create:'nueva'}

  resources :pets,
    path: 'mascotas',
    path_names: { new: "nueva", edit: "editar"}

  devise_for :users,
    controllers: { sessions: "users/sessions", registrations: 'users/registrations',
                   confirmations: "users/confirmations", passwords: 'users/passwords',
                   omniauth_callbacks: 'omniauth_callbacks'}, 
    path: "/", 
    path_names: { sign_in: 'ingresar', password: 'contraseña', sign_out: 'salir',
                  registration: 'registrarme', sign_up: '/', confirmation: 'confirmacion'}

  devise_scope :user do
    get 'dislike' => 'pets#notInterested', as: :desinteresado
    get 'like' => 'pets#interested', as: :interesado
    get 'contraseña/nueva' => 'users/passwords#new',  as: :new_password
    post 'contraseña/nueva' => 'users/passwords#create', as: :password
    get 'contraseña/editar' => 'users/passwords#edit', as: :edit_password
    match 'contraseña/editar' => 'users/passwords#update', via: [:put, :patch], as: :update_password
    get 'usuario/editar' => 'users/registrations#edit', as: :edit_user
    match 'usuario/editar' => 'users/registrations#update', via: [:put, :patch], as: :update_user
    get 'usuario/' => 'user#index', as: :user
    get 'confirmacion' => 'users/confirmations#new', as: :new_confirmation
  end
    

end

Ruby/proyectoFinal/app/models/solicitud.rb
class Solicitud < ActiveRecord::Base

	extend Enumerize
	acts_as_followable
	
	validates :nombre, :ocupacion, :por_que, :consideras, :actividades, :vivienda, :dormir, :mudarse,  presence: true
	validates :edad, numericality: { greater_than_or_equal_to: 18 } 
	enumerize :consideras, in: [:compañia, :guardia, :amigo, :familia]
	enumerize :vivienda, in: [:casa, :departamento]
	enumerize :dormir, in:[:jardin, :patio, :azotea, :casa]

	
end

Ruby/proyectoFinal/app/controllers/solicituds_controller.rb
class SolicitudsController < ApplicationController
  before_action :set_solicitud, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :log_in?, only: [:index]


  # GET /solicituds
  # GET /solicituds.json
  def index
    @solicituds = Solicitud.all
  end

  def log_in?
    if current_user
      redirect_to user_path
    end
  end

  # GET /solicituds/1
  # GET /solicituds/1.json
  def show
  end

  # GET /solicituds/new
  def new 
    @pet = Pet.friendly.find(params[:id])
    @solicitud = Solicitud.new
  end

  # GET /solicituds/1/edit
  def edit
  end

  # POST /solicituds
  # POST /solicituds.json
  def create
    @pet = Pet.find(params[:id])     
    @solicitud = Solicitud.new(solicitud_params)
    @solicitud.id = current_user.id        
    @solicitud.id_pet = @pet.id
    respond_to do |format|
      if @solicitud.save
        solicitud = Solicitud.find(@solicitud.id)
        user = User.find(current_user.id)
        #user.follow(solicitud) Esto no porque crea tuplas duplicadas y mal en followers
        format.html { redirect_to @solicitud, notice: 'Tu solicitud ha sido guardada' }
        format.json { render :show, status: :created, location: @solicitud }
      else
        format.html { render :new }
        format.json { render json: @solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicituds/1
  # PATCH/PUT /solicituds/1.json
  def update
    respond_to do |format|
      if @solicitud.update(solicitud_params)
        format.html { redirect_to @solicitud, notice: 'Solicitud was successfully updated.' }
        format.json { render :show, status: :ok, location: @solicitud }
      else
        format.html { render :edit }
        format.json { render json: @solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicituds/1
  # DELETE /solicituds/1.json
  def destroy
    @solicitud.destroy
    respond_to do |format|
      format.html { redirect_to solicituds_url, notice: 'Solicitud was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitud
      @solicitud = Solicitud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitud_params
      params.require(:solicitud).permit(:nombre, :ocupacion, :edad, :por_que, :consideras, :experiencia, :actividades, :gastos, :vivienda, :dormir, :mudarse, :ajuste)
    end
end

Ruby/proyectoFinal/app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

Ruby/proyectoFinal/app/views/solicituds/_form.html.erb
<div id="wrapper">
<div id="page-content-wrapper">
<div class="container">
 <div class="row">
 <div class="col-sm-offset-2 col-md-offset-3 col-lg-offset-4 col-xs-12 col-sm-8 col-md-6 col-lg-4">

<h3 class="omb_authTitle" style="text-align:center">Solicitud</h3>

<%= simple_form_for(@solicitud) do |f| %>
<% if alert or f.error_notification %>
<div class="alert alert-warning" role="alert">
<strong class="warning"></strong>
<%= alert %>
<%= f.error_notification %>
</div>
<% end %>
  <div class="form-inputs">
  <div class="form-group">
    <%= f.input :nombre, label:'Escribe tu nombre', autofocus: ((@solicitud.errors.include?(:nombre)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :ocupacion, label:'¿A que te dedicas?', autofocus: ((@solicitud.errors.include?(:ocupacion)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :edad, label:'¿Cual es tu edad?', autofocus: ((@solicitud.errors.include?(:edad)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :por_que, label: '¿Por que quieres adopatar una mascota?', autofocus: ((@solicitud.errors.include?(:por_que)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :consideras, label: '¿Como considerarias a tu nueva mascota?', autofocus: ((@solicitud.errors.include?(:consideras)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
      ¿Has tenido experiencia cuidando mascotas?
    </div>
    <div class="form-group">
    <%= f.input :experiencia,  as: :boolean, checked_value: true, unchecked_value: false, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :actividades, label:'¿Qué tipo de actividades planea realizar con el perro o gato que desea adoptar?', autofocus: ((@solicitud.errors.include?(:actividades)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
      ¿Conoces cuales son los gastos economicos qe involucran tener mascota?
    </div>
    <div class="form-group">
    <%= f.input :gastos, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :vivienda, label:'¿En donde vives?', autofocus: ((@solicitud.errors.include?(:vivienda)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
    <%= f.input :dormir, label:'¿En donde dormiria la mascota?', autofocus: ((@solicitud.errors.include?(:dormir)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>    
    <div class="form-group">
    <%= f.input :mudarse, label:'¿Qué sucedería si tuviera que mudarse a otra casa o ciudad /país? ', autofocus: ((@solicitud.errors.include?(:mudarse)) ? true : false), required: true, input_html: { class:'form-control' } %>
    </div>
    <div class="form-group">
       ¿Está dispuesto a que el perro o gato tenga un periodo de ajuste en el que aprenda dónde debe ir al baño y se adapte a la familia? 
    </div>
    <div class="form-group">
    <%= f.input :ajuste, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class:'form-control' } %>
    </div>    
  </div>

  <%= hidden_field_tag(:id, @pet.id) %>  
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>
  </div>
  </div>
  </div>
  </div>
  </div>
 <script>
    var AutoResizer = function (textArea, options) {
    var self = this;

    this.$textArea = $(textArea);
    this.minHeight = this.$textArea.height();

    this.options = $.extend({}, $.fn.autoResizer.defaults, options)

    this.$shadowArea = $('<div></div>').css({
        position: 'absolute',
        top: -10000,
        left: -10000,
        fontSize: this.$textArea.css('fontSize') || 'inherit',
        fontFamily: this.$textArea.css('fontFamily') || 'inherit',
        lineHeight: this.$textArea.css('lineHeight') || 'inherit',

        /* this helps a bit */
        paddingTop: this.$textArea.css('paddingTop') || 'inherit',
        paddingBottom: this.$textArea.css('paddingBottom') || 'inherit',
        paddingLeft: this.$textArea.css('paddingLeft') || 'inherit',
        paddingRight: this.$textArea.css('paddingRight') || 'inherit',

        /*
        But once you add borders to a box-sizing: border-box textarea,
        things go very wrong and this doesn't help.
        */
        borderTopWidth: this.$textArea.css('borderTopWidth') || 'inherit',
        borderBottomWidth: this.$textArea.css('borderBottomWidth') || 'inherit',
        borderLeftWidth: this.$textArea.css('borderLeftWidth') || 'inherit',
        borderRightWidth: this.$textArea.css('borderRightWidth') || 'inherit',
        
        resize: 'none'
      }).appendTo(document.body);

    var startWidth = this.$textArea.width() || $(window).width();
    this.$shadowArea.width(startWidth);
    
    if (this.options.resizeOnChange) {
      function onChange() {
        window.setTimeout(function() {
          self.checkResize();
        }, 0);
      }
      this.$textArea.change(onChange).keyup(onChange).keydown(onChange).focus(onChange);
    }

    this.checkResize();
  };

   AutoResizer.prototype = {
    constructor: AutoResizer,
    checkResize: function() {
      // No sense in auto-growing non-visible textarea, which height of 0 implies
      if (this.$textArea.height() === 0) {
        return;
      }
      // If this is first time we've seen text area rendered, remember the height
      if (this.minHeight === 0) {
        this.minHeight = this.$textArea.height();
      }
      // If the text area has changed in size past a certain threshold of difference
      // like when it becomes visible or viewport changes
      if (this.$textArea.width() !== 0 && Math.abs(this.$shadowArea.width() - this.$textArea.width()) > 20) {
        this.$shadowArea.width(this.$textArea.width());
      }

      var val = this.$textArea.val().replace(/</g, '&lt;')
              .replace(/>/g, '&gt;')
              .replace(/&/g, '&amp;')
              .replace(/\n/g, '<br/>&nbsp;');

      if ($.trim(val) === '') {
          val = 'a';
      }
      this.$shadowArea.html(val);
      var nextHeight =  Math.max(this.$shadowArea[0].offsetHeight + 20, this.minHeight);
      if (!this.prevHeight || nextHeight != this.prevHeight) {
        this.$textArea.css('height', nextHeight);
        this.prevHeight = nextHeight;
      }
    }
  };


  $.fn.autoResizer = function ( option ) {
    return this.each(function () {
      var $this = $(this)
        , data = $this.data('autoresizer')
        , options = typeof option == 'object' && option
      if (!data) $this.data('autoresizer', (data = new AutoResizer(this, options)))
      if (typeof option == 'string') data[option]()
      else data.checkResize()
    })
  }

  $.fn.autoResizer.defaults = {
    resizeOnChange: true
  };

  $.fn.autoResizer.Constructor = AutoResizer;
      
  $('textarea').autoResizer();
  </script>

Ruby/proyectoFinal/app/views/solicituds/edit.html.erb
<h1>Editing Solicitud</h1>

<%= render 'form' %>

<%= link_to 'Show', @solicitud %> |
<%= link_to 'Back', solicituds_path %>

Ruby/proyectoFinal/app/views/solicituds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Solicituds</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ocupacion</th>
      <th>Edad</th>
      <th>Por que</th>
      <th>Consideras</th>
      <th>Experiencia</th>
      <th>Actividades</th>
      <th>Gastos</th>
      <th>Vivienda</th>
      <th>Dormir</th>
      <th>Mudarse</th>
      <th>Ajuste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solicituds.each do |solicitud| %>
      <tr>
        <td><%= solicitud.nombre %></td>
        <td><%= solicitud.ocupacion %></td>
        <td><%= solicitud.edad %></td>
        <td><%= solicitud.por_que %></td>
        <td><%= solicitud.consideras %></td>
        <td><%= solicitud.experiencia %></td>
        <td><%= solicitud.actividades %></td>
        <td><%= solicitud.gastos %></td>
        <td><%= solicitud.vivienda %></td>
        <td><%= solicitud.dormir %></td>
        <td><%= solicitud.mudarse %></td>
        <td><%= solicitud.ajuste %></td>
        <td><%= link_to 'Show', solicitud %></td>
        <td><%= link_to 'Edit', edit_solicitud_path(solicitud) %></td>
        <td><%= link_to 'Destroy', solicitud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solicitud', new_solicitud_path %>

Ruby/proyectoFinal/app/views/solicituds/new.html.erb
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div clas="container">
          <a class="navbar-brand" href="">
            <i class="fa fa-paw fa-4"></i>
            <div class="content-hidden">Mascotas</div>
          </a>
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to user_path, :class => 'nav-link' do%>
                <%= fa_icon "home"%> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path(kms: 5), :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to my_pets_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "list"%> <div class="content-hidden">Mis Publicaciones</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_pet_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square" %> <div class="content-hidden">Publicar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to edit_user_path, class:"nav-link" do %>
                <%= fa_icon "pencil" %> <div class="content-hidden">Editar Cuenta</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: 'delete', class:"nav-link" do %>
                <%= fa_icon "sign-out" %> <div class="content-hidden">Salir</div>
              <% end %>
            </li>
          </ul>
        </div> <!-- fin de nav -->
      </nav>

      <br/><br/> <!-- Agregar espacio entre el header y body--> 

      <nav>
        <ul class="pager">
          <li><%= link_to '« Cancelar', pet_path(@pet) %></li>
        </ul>
      </nav>

      <%= render 'form' %>

Ruby/proyectoFinal/app/views/solicituds/show.html.erb
      <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div clas="container">
          <a class="navbar-brand" href="">
            <i class="fa fa-paw fa-4"></i>
            <div class="content-hidden">Mascotas</div>
          </a>
          <ul class="nav navbar-nav collapsed pull-xs-right">
            <li class="nav-item">
              <%= link_to user_path, :class => 'nav-link' do%>
                <%= fa_icon "home"%> <div class="content-hidden">Inicio</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to search_pet_path(kms: 5), :class => 'nav-link' do%>
                <%= fa_icon "search"%> <div class="content-hidden">Buscar</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to my_pets_pet_path, :class => 'nav-link' do%>
                <%= fa_icon "list"%> <div class="content-hidden">Mis Publicaciones</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to new_pet_path, class:"nav-link" do %>
                <%= fa_icon "pencil-square" %> <div class="content-hidden">Publicar</div>
              <% end %>
            </li>
            <li class="nav-item ">
              <%= link_to edit_user_path, class:"nav-link" do %>
                <%= fa_icon "pencil" %> <div class="content-hidden">Editar Cuenta</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: 'delete', class:"nav-link" do %>
                <%= fa_icon "sign-out" %> <div class="content-hidden">Salir</div>
              <% end %>
            </li>
          </ul>
        </div><!-- bs-example-navbar-collapse-1 -->
      </nav>

      <br/>
      <br/>
      <nav>
        <ul class="pager">
          <li><%= link_to '« Inicio', user_path %></li>
        </ul>
      </nav>

      <div id="wrapper">
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="sol">
            <center>
            <table>
            <div class='solicitud'>            
                <tr>
                  <td class='sol'><center>Nombre:</center></td>
                  <td class='sol'><%= @solicitud.nombre %></td>
                </tr>                              
            </div>
            <div class='solicitud'>            
                <tr>
                  <td class='sol'><center>Ocupacion:</center></td>
                  <td class='sol'><%= @solicitud.ocupacion %></td>
                </tr>                              
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Edad:</center></td>
                  <td class='sol'><%= @solicitud.edad %></td>
                </tr>                              
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Por que quiero una mascota :</center></td>
                  <td class='sol'><%= @solicitud.por_que %></td>
                </tr>                                                                                            
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Como considero a mi mascota:</center></td>
                  <td class='sol'>  <%= @solicitud.consideras %></td>
                </tr>                              
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Experiencia cuidando mascotas:</center></td>
                  <td class='sol'><%if @solicitud.experiencia ==false%>
                No
              <%else%>
              Si
              <%end%></td>
                </tr>
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Actividades que realizaria con mi mascota:</center></td>
                  <td class='sol'><%= @solicitud.actividades %></td>
                </tr> 
            </div>
            <div class='solicitud'>
                <tr>
                  <td class='sol'><center>Conosco los gastos economicos:</center></td>
                  <td class='sol'><%if @solicitud.gastos ==false%>
                        No
                        <%else%>
                        Si
                        <%end%>
                  </td>
                </tr>                
            </div>
            <div class='solicitud'>
                <tr>
                  <td class='sol'><center>Vivo en :</center></td>
                  <td class='sol'><%= @solicitud.vivienda %></td>
                </tr>                                                                                      
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>La mascota dormiria en :</center></td>
                  <td class='sol'><%= @solicitud.dormir %></td>
                </tr>                
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Si me mudara mi mascota :</center></td>
                  <td class='sol'><%= @solicitud.mudarse %></td>
                </tr>                
            </div>
            <div class='solicitud'>              
                <tr>
                  <td class='sol'><center>Estoy dispuesto a que la mascota se adapte a su nuevo entorno :</center></td>
                  <td class='sol'><%if @solicitud.ajuste==false%>
                        No
                      <%else%>
                        Si
                      <%end%>
                  </td>
                </tr>                              
            </div>
            </table>                                                        
            </center>
          </div>
        </div><!-- /#page-content-wrapper -->
      </div><!-- /#wrapper -->